### ISSUE TITLE
What am I doing wrong here. 

### ISSUE THREAD

**Issue by thelawrencearm** [KennethScott/SpecOps#10]
I followed the basic instructions, and try a couple of versions but all I get is the AdminLT3  page.

![image](https://user-images.githubusercontent.com/20508294/233716175-736bc574-c3d9-42b9-a744-8ec5791b8b60.png)

**Comment by KennethScott** [comment]
What URL are you accessing exactly?

**Comment by thelawrencearm** [comment]
Hi! Thanks for the reply.  If I use the path of c:\specops which is the extracted precompiled zip and browse to http://localhost:80 I get "Internal Error 500.19. 

 If I use the path c:\specops\wwwroot an browse to local host I get the Admin LTE3 dashboard.

Ive tried every folder and a couple of releases but can't seem to figure this one out. I am running a fresh 2019 server 

![image](https://user-images.githubusercontent.com/20508294/233758298-49cf1f57-9629-43e7-9357-6662885d117e.png)
 
![image](https://user-images.githubusercontent.com/20508294/233758330-c3d7469b-2b36-4e66-a760-53158bbfdac5.png)

**Comment by thelawrencearm** [comment]
I worked through the wiki again.  I am still having issues though
1) Reinstalled DontNet hosting core 7.0.5
2) Made an Application under Default Website and used the AppPool
c:\specops\

- browsing to localhost brings me to AdminLTE page. 
- Browsing to https://localhost/specops  shows connection refused. 


![image](https://user-images.githubusercontent.com/20508294/233805196-600969e6-4a3b-4539-9031-875543985331.png)

![image](https://user-images.githubusercontent.com/20508294/233805231-d1d383da-5e36-4653-98f3-ae71a7eb9a2a.png)

**Comment by KennethScott** [comment]
Hmm..  couple thoughts..

Connection refused could be firewall - have you tried disabling it to see if that's it?

Normally you'll simply extract the zip to a folder - let's say C:\SpecOps - but i will warn you that Server 2019 is more restricted about allowing access to areas on the file system - particularly the root in my experience.   You might want to create a SpecOps folder wherever the IIS root is configured - probably C:\inetpub\wwwroot.   So maybe try extracting there so that you wind up with c:\inetpub\wwwroot\SpecOps.

You should be able to test access to the path by making sure you have your SpecOps site highlighted in IIS, and then clicking Basic Settings over on the right, and using the "Test Settings" button:

![image](https://user-images.githubusercontent.com/823499/233808352-c6b18a32-44ea-4de1-9294-5f42842d4a74.png)

Once you make sure your SpecOps site in IIS is now pointed at your updated path (and the access test is successful), it should simply be a matter of launching your browser to https://localhost/specops

One other thing I did realize when I just did a little test earlier was that it's currently configured to redirect from http to https automatically.  I should probably change that in the release so it'll work with either, because some people may not have a cert installed on the server to allow https (if not, you can do a self-signed one).  You'll just need to check the bindings on the site for https and make sure it's set to a valid cert:

![image](https://user-images.githubusercontent.com/823499/233808271-b73bca42-4d97-4cbe-9624-7930f88d1c9d.png)

![image](https://user-images.githubusercontent.com/823499/233808284-76169d1d-f47a-497a-aaad-74391628da4c.png)

If you get past the connection refused and then you're getting "The connection was reset" - you'll likely need to check the cert. 
 if you can't get a cert installed, let me know and I'll publish a version with the http-to-https redirect disabled.

Let me know-

**Comment by thelawrencearm** [comment]
I appreciate the help! I think im closer. Not sure what I did.. Im testing on a 2016 server with the same results too... but now I get Access to localhost denied.  Anonymous auth is off. Windows auth is on.  Folder permissions are right. tired moving to inetpub. same thing.    SSL cert didn't make difference.   

![image](https://user-images.githubusercontent.com/20508294/233813353-0eb79d98-71d2-40f8-ae7a-52f1d083a983.png)

**Comment by KennethScott** [comment]
Now that is coming from the app!  Add yourself to the JSON config file as
an admin and it should come up!

**Comment by thelawrencearm** [comment]
HUZZAH!!!!  THANK YOU SIR!!!   Ill retrace my steps and document it and send it over.   

thanks again!

**Comment by KennethScott** [comment]
Glad you got it working!
